### PR TITLE
fix(ListingDetail): display description w/ newlines intact

### LINKED ISSUE #503: Split text description input by newline
Split text description input by newlines, then iterate over contents and output as an array inside the product listing component's description

related to #500 but a lot simpler and addresses the use case @aeluteia wrote about in chat

### PR DESCRIPTION
**Pull request by lbsal**
closes #503

note: This patch assumes that `<listing>.Metadata.Description` will always be a string

Tangentially related to #500

### CODE REVIEW

File: packages/frontend/src/components/ListingDetail.tsx [hunk 1]
```diff
@@ -221,7 +225,15 @@ export default function ListingDetail() {
           <section className="flex gap-4 flex-col bg-white mt-5 md:mt-0 rounded-md md:w-2/5 p-4">
             <div>
               <h3 className=" ">Description</h3>
-              <p data-testid="description">{listing.Metadata.Description}</p>
+              <section data-testid="description">
+                {splitTextByNewlines(listing.Metadata.Description).map(
+                  (line: string, index: number) => (
+                    <p key={`description-${index}`} className="min-h-[1ch]">
```
Comment (cryptix) [inline packages/frontend/src/components/ListingDetail.tsx:231]: pr525-2025-05-19
just a minor quibble / react learning Q: is the `key` property special somehow?

**Review by cryptix — APPROVED** [review]
tried it and works!
